version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=gitpod
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_DB: example
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: